openapi: 3.1.0
info:
  title: WakandansHR DB API,
  version: apiVersion,
  description: |
    The HR DB API is a RESTful API that provides access to the HR database.

    API possible responses: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses

    Informational responses (100 - 199)

    Successful responses (200 - 299)

    Redirection messages (300 - 399)

    Client error responses (400 - 499)

    Server error responses (500 - 599)

servers:
  - url: http://localhost:5000/api/v1
    description: Development server
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session
security:
  - cookieAuth: []
paths:
  /hello:
    get:
      summary: A simple hello world endpoint
      tags:
        - Hello
      security: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Hello, World!'
  /locations:
    get:
      summary: Get all locations
      tags:
        - Locations
      parameters:
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: A list of locations
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: 'New York Office'
                    country:
                      type: string
                      example: 'US'
                    city:
                      type: string
                      example: 'New York'
                    address:
                      type: string
                      example: '5th Street - Building 100, first floor'
    post:
      summary: Create a new location
      tags:
        - Locations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'New York Office'
                country:
                  type: string
                  example: 'US'
                city:
                  type: string
                  example: 'New York'
                address:
                  type: string
                  example: '5th Street - Building 100, first floor'
                workSettingId:
                  type: integer
                  example: 2
      responses:
        201:
          description: Location created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
  /locations/count:
    get:
      summary: Retrieves the count of locations
      tags:
        - Locations
      responses:
        200:
          description: The count of departments
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 10
  /locations/{locationId}:
    get:
      summary: Retrieve a specific location by ID
      tags:
        - Locations
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the location
      responses:
        200:
          description: A location
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: 'New York Office'
                  country:
                    type: string
                    example: 'US'
                  city:
                    type: string
                    example: 'New York'
                  address:
                    type: string
                    example: '5th Street - Building 100, first floor'
                  workSetting:
                    type: object
                  users:
                    type: array
                    items:
                      type: object
                  departments:
                    type: array
                    items:
                      type: object
                  teams:
                    type: array
                    items:
                      type: object
                  groups:
                    type: array
                    items:
                      type: object
                  locationStatuses:
                    type: array
                    items:
                      type: object
                  daysOffLocation:
                    type: array
                    items:
                      type: object
    put:
      summary: Update a location by ID
      tags:
        - Locations
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the location
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'New York Office'
                country:
                  type: string
                  example: 'US'
                city:
                  type: string
                  example: 'New York'
                address:
                  type: string
                  example: '5th Street - Building 100, first floor'
                workSettingId:
                  type: integer
                  example: 2
      responses:
        200:
          description: Location updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: 'Location updated successfully'
    delete:
      summary: Delete a location by ID
      tags:
        - Locations
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the location
      responses:
        200:
          description: Location deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: 'Location deleted successfully'
  /login:
    post:
      summary: Generate a login token for a user
      tags:
        - Authentication
      requestBody:
        description: The email address of the user requesting a login token
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: 'user@example.com'
      security: []
      responses:
        200:
          description: Login token generated and email job created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Login token generated and email job created successfully'
  /validate-token:
    post:
      summary: Validate a login token
      tags:
        - Authentication
      requestBody:
        description: The email address and login token to validate
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: 'user@example.com'
                loginToken:
                  type: string
                  example: '4c2fdef7-9d3b-4c2d-a1b6-9c2bfc51900b'
      security: []
      responses:
        200:
          description: Login token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Login token is valid'
  /logout:
    post:
      summary: User logout
      tags:
        - Authentication
      requestBody:
        description: No request body required.
        required: false
        content: {}
      responses:
        '200':
          description: Successfully logged out.
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      description: Fetch a paginated list of users.
      parameters:
        - name: page
          in: query
          description: The page number (0-based).
          required: false
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          description: The number of users to retrieve per page.
          required: false
          schema:
            type: integer
            default: 10
      responses:
        200:
          description: Successful response with user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/MinimalUser'
                  next:
                    type: boolean
                    description: Indicates if there are more pages.
        500:
          description: Server error
    post:
      tags:
        - Users
      summary: Create a new user
      description: Add a new user to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                firstName:
                  type: string
                lastName:
                  type: string
                role:
                  type: string
                  enum:
                    - Admin
                    - User
                locationId:
                  type: integer
                reportsToId:
                  type: integer
      responses:
        201:
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        500:
          description: Server error

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get a user by ID
      description: Fetch details of a specific user by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to retrieve.
          schema:
            type: integer
      responses:
        200:
          description: Successful response with user data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User not found
        500:
          description: Server error
    put:
      tags:
        - Users
      summary: Update a user
      description: Update details of a specific user by ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        200:
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid user ID
        500:
          description: Server error
    patch:
      tags:
        - Users
      summary: Soft delete a user
      description: Mark a user as inactive and set a deletion timestamp.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to soft delete.
          schema:
            type: integer
      responses:
        200:
          description: User soft-deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Invalid user ID
        500:
          description: Server error
  /departments:
    get:
      summary: Get all departments
      tags:
        - Departments
      parameters:
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 10
        - name: page
          in: query
          description: Page number
          required: false
          schema:
            type: integer
            default: 0
      responses:
        200:
          description: A list of departments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: 'Engineering'
                    description:
                      type: string
                      example: 'Handles all engineering tasks'
    post:
      summary: Create a new department
      tags:
        - Departments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'Engineering'
                description:
                  type: string
                  example: 'Handles all engineering tasks'
                locationId:
                  type: integer
                  example: 2
      responses:
        201:
          description: Department created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1

  /departments/{departmentId}:
    get:
      summary: Retrieve a specific department by ID
      tags:
        - Departments
      parameters:
        - name: departmentId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the department
      responses:
        200:
          description: A department
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  name:
                    type: string
                    example: 'Engineering'
                  description:
                    type: string
                    example: 'Handles all engineering tasks'
                  location:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 2
                      name:
                        type: string
                        example: 'New York Office'
    put:
      summary: Update a department by ID
      tags:
        - Departments
      parameters:
        - name: departmentId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the department
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: 'Engineering'
                description:
                  type: string
                  example: 'Handles all engineering tasks'
      responses:
        200:
          description: Department updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: 'Department updated successfully'
    patch:
      summary: Soft delete a department by ID
      tags:
        - Departments
      parameters:
        - name: departmentId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the department
      responses:
        200:
          description: Department soft-deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: 'Department soft-deleted successfully'
components:
  schemas:
    MinimalDepartment:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
    Department:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        location:
          $ref: '#/components/schemas/MinimalLocation'
    MinimalLocation:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string


components:
  schemas:
    MinimalUser:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email
        role:
          type: string
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        role:
          type: string
          enum:
            - Admin
            - User