#!/bin/sh

set -e

export PGPASSWORD=$POSTGRES_PASSWORD

until psql -h $DB_HOST -p $DB_PORT -U $POSTGRES_USER -d $POSTGRES_DB -c '\q'; do
  >&2 echo "Postgres is unavailable - sleeping // psql -h $DB_HOST -p $DB_PORT -U $POSTGRES_USER -d $POSTGRES_DB "
  sleep 1
done
  
>&2 echo "Postgres is up, creating users and granting permissions"

psql -h $DB_HOST -p $DB_PORT -U $POSTGRES_USER -d $POSTGRES_DB <<-EOSQL
  CREATE USER ${READ_USER} WITH PASSWORD '$READ_PASSWORD';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${READ_USER};
  GRANT USAGE ON SCHEMA public TO ${READ_USER};

  CREATE USER ${WRITE_USER} WITH PASSWORD '${WRITE_PASSWORD}';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${WRITE_USER};
  GRANT USAGE ON SCHEMA public TO ${WRITE_USER};

  CREATE USER ${ADMIN_USER} WITH PASSWORD '${ADMIN_PASSWORD}';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${ADMIN_USER};
  GRANT USAGE ON SCHEMA private TO ${ADMIN_USER};
  
  CREATE USER ${JOBS_USER} WITH PASSWORD '${JOBS_PASSWORD}';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${JOBS_USER};
  GRANT USAGE ON SCHEMA jobs TO ${JOBS_USER};
EOSQL

npx prisma migrate deploy

psql -h $DB_HOST -p $DB_PORT -U $POSTGRES_USER -d $POSTGRES_DB <<-EOSQL
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${READ_USER};
  GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO ${WRITE_USER};
  GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA private TO ${ADMIN_USER};
  GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA jobs TO ${JOBS_USER};

  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${WRITE_USER};
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA private TO ${ADMIN_USER};
  GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA jobs TO ${JOBS_USER};
EOSQL

unset PGPASSWORD