import { UserRole } from '@prisma/client';
import { writePrisma } from '../prisma';

const users = [
  // Admins, reporting to no one
  {
    firstName: 'Alexi',
    lastName: 'Akl',
    email: 'alexi.akl@example.co',
    locationId: 3,
    role: 'ADMIN',
    reportsToId: null,
    workSettingId: null,
  },
  {
    firstName: 'Josh',
    lastName: 'Hanks',
    email: 'josh.hanks@example.co',
    locationId: 2,
    role: 'ADMIN',
    reportsToId: null,
    workSettingId: null,
  },
  {
    firstName: 'Dany',
    lastName: 'Drac',
    email: 'dany.drac@example.co',
    locationId: 1,
    role: 'ADMIN',
    reportsToId: null,
    workSettingId: null,
  },
  {
    firstName: 'James',
    lastName: 'Brown',
    email: 'james.brown@example.co',
    locationId: 2,
    role: 'ADMIN',
    reportsToId: null,
    workSettingId: null,
  },
  {
    firstName: 'Olivia',
    lastName: 'Jones',
    email: 'olivia.jones@example.co',
    locationId: 1,
    role: 'MANAGER',
    reportsToId: 1,
    workSettingId: null,
  },
  {
    firstName: 'Lucas',
    lastName: 'Garcia',
    email: 'lucas.garcia@example.co',
    locationId: 1,
    role: 'MANAGER',
    reportsToId: 1,
    workSettingId: null,
  },
  {
    firstName: 'Emma',
    lastName: 'Martinez',
    email: 'emma.martinez@example.co',
    locationId: 1,
    role: 'MANAGER',
    reportsToId: 1,
    workSettingId: null,
  },
  {
    firstName: 'Noah',
    lastName: 'Hernandez',
    email: 'noah.hernandez@example.co',
    locationId: 1,
    role: 'MANAGER',
    reportsToId: 2,
    workSettingId: null,
  },
  {
    firstName: 'Liam',
    lastName: 'Clark',
    email: 'liam.clark@example.co',
    locationId: 1,
    role: 'MANAGER',
    reportsToId: 2,
    workSettingId: null,
  },
  {
    firstName: 'Ava',
    lastName: 'Rodriguez',
    email: 'ava.rodriguez@example.co',
    locationId: 1,
    role: 'MANAGER',
    reportsToId: 2,
    workSettingId: null,
  },
  {
    firstName: 'Ethan',
    lastName: 'Lee',
    email: 'ethan.lee@example.co',
    locationId: 1,
    role: 'MANAGER',
    reportsToId: 2,
    workSettingId: null,
  },
  {
    firstName: 'Isabella',
    lastName: 'Walker',
    email: 'isabella.walker@example.co',
    locationId: 1,
    role: 'MANAGER',
    reportsToId: 3,
    workSettingId: null,
  },
  {
    firstName: 'William',
    lastName: 'Hall',
    email: 'william.hall@example.co',
    locationId: 1,
    role: 'MANAGER',
    reportsToId: 3,
    workSettingId: null,
  },
  {
    firstName: 'Mia',
    lastName: 'Allen',
    email: 'mia.allen@example.co',
    locationId: 2,
    role: 'MANAGER',
    reportsToId: 4,
    workSettingId: null,
  },
  {
    firstName: 'Benjamin',
    lastName: 'Young',
    email: 'benjamin.young@example.co',
    locationId: 2,
    role: 'MANAGER',
    reportsToId: 4,
    workSettingId: null,
  },
  {
    firstName: 'Charlotte',
    lastName: 'King',
    email: 'charlotte.king@example.co',
    locationId: 2,
    role: 'MANAGER',
    reportsToId: 4,
    workSettingId: null,
  },
  {
    firstName: 'Jack',
    lastName: 'Wright',
    email: 'jack.wright@example.co',
    locationId: 2,
    role: 'MANAGER',
    reportsToId: 4,
    workSettingId: null,
  },
  {
    firstName: 'Amelia',
    lastName: 'Scott',
    email: 'amelia.scott@example.co',
    locationId: 2,
    role: 'MANAGER',
    reportsToId: 4,
    workSettingId: null,
  },
  {
    firstName: 'Alexander',
    lastName: 'Green',
    email: 'alexander.green@example.co',
    locationId: 2,
    role: 'MANAGER',
    reportsToId: 4,
    workSettingId: null,
  },
  {
    firstName: 'Ethan',
    lastName: 'Roberts',
    email: 'ethan.roberts@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 5,
    workSettingId: null,
  },
  {
    firstName: 'Ella',
    lastName: 'Lewis',
    email: 'ella.lewis@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 5,
    workSettingId: null,
  },
  {
    firstName: 'Jacob',
    lastName: 'Harris',
    email: 'jacob.harris@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 5,
    workSettingId: null,
  },
  {
    firstName: 'Lily',
    lastName: 'Clarkson',
    email: 'lily.clarkson@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 6,
    workSettingId: null,
  },
  {
    firstName: 'Mason',
    lastName: 'Lewis',
    email: 'mason.lewis@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 6,
    workSettingId: null,
  },
  {
    firstName: 'Aiden',
    lastName: 'Robinson',
    email: 'aiden.robinson@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 6,
    workSettingId: null,
  },
  {
    firstName: 'Sophie',
    lastName: 'Turner',
    email: 'sophie.turner@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 6,
    workSettingId: null,
  },
  {
    firstName: 'James',
    lastName: 'Perry',
    email: 'james.perry@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 7,
    workSettingId: null,
  },
  {
    firstName: 'Grace',
    lastName: 'Reed',
    email: 'grace.reed@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 7,
    workSettingId: null,
  },
  {
    firstName: 'Alexander',
    lastName: 'Morgan',
    email: 'alexander.morgan@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 7,
    workSettingId: null,
  },
  {
    firstName: 'Chloe',
    lastName: 'Stewart',
    email: 'chloe.stewart@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 7,
    workSettingId: null,
  },
  {
    firstName: 'Daniel',
    lastName: 'Bell',
    email: 'daniel.bell@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 7,
    workSettingId: null,
  },
  {
    firstName: 'Zoe',
    lastName: 'Parker',
    email: 'zoe.parker@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 7,
    workSettingId: null,
  },
  {
    firstName: 'Oliver',
    lastName: 'Mitchell',
    email: 'oliver.mitchell@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 8,
    workSettingId: null,
  },
  {
    firstName: 'Scarlett',
    lastName: 'Simmons',
    email: 'scarlett.simmons@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 8,
    workSettingId: null,
  },
  {
    firstName: 'Ryan',
    lastName: 'Foster',
    email: 'ryan.foster@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 8,
    workSettingId: null,
  },
  {
    firstName: 'Emily',
    lastName: 'Collins',
    email: 'emily.collins@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 9,
    workSettingId: null,
  },
  {
    firstName: 'Matthew',
    lastName: 'Bennett',
    email: 'matthew.bennett@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 9,
    workSettingId: null,
  },
  {
    firstName: 'Layla',
    lastName: 'Adams',
    email: 'layla.adams@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 9,
    workSettingId: null,
  },
  {
    firstName: 'Joshua',
    lastName: 'Nelson',
    email: 'joshua.nelson@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 9,
    workSettingId: null,
  },
  {
    firstName: 'Hannah',
    lastName: 'Murphy',
    email: 'hannah.murphy@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 9,
    workSettingId: null,
  },
  {
    firstName: 'Nathan',
    lastName: 'Rivera',
    email: 'nathan.rivera@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 10,
    workSettingId: null,
  },
  {
    firstName: 'Alyssa',
    lastName: 'Ward',
    email: 'alyssa.ward@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 10,
    workSettingId: null,
  },
  {
    firstName: 'Caleb',
    lastName: 'Baker',
    email: 'caleb.baker@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 10,
    workSettingId: null,
  },
  {
    firstName: 'Mila',
    lastName: 'Brooks',
    email: 'mila.brooks@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 10,
    workSettingId: null,
  },
  {
    firstName: 'Liam',
    lastName: 'Kelly',
    email: 'liam.kelly@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 10,
    workSettingId: null,
  },
  {
    firstName: 'Emma',
    lastName: 'Sanders',
    email: 'emma.sanders@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 10,
    workSettingId: null,
  },
  {
    firstName: 'Charlotte',
    lastName: 'Gonzalez',
    email: 'charlotte.gonzalez@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 11,
    workSettingId: null,
  },
  {
    firstName: 'Zachary',
    lastName: 'Howard',
    email: 'zachary.howard@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 11,
    workSettingId: null,
  },
  {
    firstName: 'Isabella',
    lastName: 'Torres',
    email: 'isabella.torres@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 11,
    workSettingId: null,
  },
  {
    firstName: 'Logan',
    lastName: 'Peterson',
    email: 'logan.peterson@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 12,
    workSettingId: null,
  },
  {
    firstName: 'Avery',
    lastName: 'Cooper',
    email: 'avery.cooper@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 12,
    workSettingId: null,
  },
  {
    firstName: 'Jackson',
    lastName: 'Cox',
    email: 'jackson.cox@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 12,
    workSettingId: null,
  },
  {
    firstName: 'Aria',
    lastName: 'Richardson',
    email: 'aria.richardson@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 12,
    workSettingId: null,
  },
  {
    firstName: 'Dylan',
    lastName: 'Wood',
    email: 'dylan.wood@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 13,
    workSettingId: null,
  },
  {
    firstName: 'Victoria',
    lastName: 'Bell',
    email: 'victoria.bell@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 13,
    workSettingId: null,
  },
  {
    firstName: 'Elijah',
    lastName: 'Carter',
    email: 'elijah.carter@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 13,
    workSettingId: null,
  },
  {
    firstName: 'Lillian',
    lastName: 'Wells',
    email: 'lillian.wells@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 13,
    workSettingId: null,
  },
  {
    firstName: 'Grace',
    lastName: 'Simmons',
    email: 'grace.simmons@example.co',
    locationId: 1,
    role: 'EMPLOYEE',
    reportsToId: 13,
    workSettingId: null,
  },
  {
    firstName: 'Aaron',
    lastName: 'Flores',
    email: 'aaron.flores@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 14,
    workSettingId: null,
  },
  {
    firstName: 'Samantha',
    lastName: 'Griffin',
    email: 'samantha.griffin@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 14,
    workSettingId: null,
  },
  {
    firstName: 'Henry',
    lastName: 'Edwards',
    email: 'henry.edwards@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 14,
    workSettingId: null,
  },
  {
    firstName: 'Ella',
    lastName: 'Kim',
    email: 'ella.kim@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 14,
    workSettingId: null,
  },
  {
    firstName: 'Evan',
    lastName: 'Jenkins',
    email: 'evan.jenkins@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 14,
    workSettingId: null,
  },
  {
    firstName: 'Abigail',
    lastName: 'Martin',
    email: 'abigail.martin@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 15,
    workSettingId: null,
  },
  {
    firstName: 'Leo',
    lastName: 'Sanders',
    email: 'leo.sanders@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 15,
    workSettingId: null,
  },
  {
    firstName: 'Maya',
    lastName: 'Rogers',
    email: 'maya.rogers@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 15,
    workSettingId: null,
  },
  {
    firstName: 'Luke',
    lastName: 'Fisher',
    email: 'luke.fisher@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 15,
    workSettingId: null,
  },
  {
    firstName: 'Natalie',
    lastName: 'Collins',
    email: 'natalie.collins@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 16,
    workSettingId: null,
  },
  {
    firstName: 'Gabriel',
    lastName: 'Bryant',
    email: 'gabriel.bryant@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 16,
    workSettingId: null,
  },
  {
    firstName: 'Ariana',
    lastName: 'Watson',
    email: 'ariana.watson@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 16,
    workSettingId: null,
  },
  {
    firstName: 'Hunter',
    lastName: 'Gonzalez',
    email: 'hunter.gonzalez@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 16,
    workSettingId: null,
  },
  {
    firstName: 'Savannah',
    lastName: 'James',
    email: 'savannah.james@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 16,
    workSettingId: null,
  },
  {
    firstName: 'Owen',
    lastName: 'Rivera',
    email: 'owen.rivera@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 17,
    workSettingId: null,
  },
  {
    firstName: 'Madison',
    lastName: 'Morgan',
    email: 'madison.morgan@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 17,
    workSettingId: null,
  },
  {
    firstName: 'Isaac',
    lastName: 'Hughes',
    email: 'isaac.hughes@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 17,
    workSettingId: null,
  },
  {
    firstName: 'Addison',
    lastName: 'Cook',
    email: 'addison.cook@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 17,
    workSettingId: null,
  },
  {
    firstName: 'Julian',
    lastName: 'Nelson',
    email: 'julian.nelson@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 18,
    workSettingId: null,
  },
  {
    firstName: 'Stella',
    lastName: 'Cruz',
    email: 'stella.cruz@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 18,
    workSettingId: null,
  },
  {
    firstName: 'Samuel',
    lastName: 'Morales',
    email: 'samuel.morales@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 18,
    workSettingId: null,
  },
  {
    firstName: 'Hazel',
    lastName: 'Price',
    email: 'hazel.price@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 18,
    workSettingId: null,
  },
  {
    firstName: 'Nathaniel',
    lastName: 'Long',
    email: 'nathaniel.long@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 18,
    workSettingId: null,
  },
  {
    firstName: 'Brooke',
    lastName: 'Ross',
    email: 'brooke.ross@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 19,
    workSettingId: null,
  },
  {
    firstName: 'Eli',
    lastName: 'Reed',
    email: 'eli.reed@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 19,
    workSettingId: null,
  },
  {
    firstName: 'Victoria',
    lastName: 'Flores',
    email: 'victoria.flores@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 19,
    workSettingId: null,
  },
  {
    firstName: 'Caroline',
    lastName: 'Cox',
    email: 'caroline.cox@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 19,
    workSettingId: null,
  },
  {
    firstName: 'Henry',
    lastName: 'Powell',
    email: 'henry.powell@example.co',
    locationId: 2,
    role: 'EMPLOYEE',
    reportsToId: 19,
    workSettingId: null,
  },
];

const usersDepartments = [
  // Engineering Department
  { userId: 1, departmentId: 1 },
  { userId: 2, departmentId: 1 },
  { userId: 3, departmentId: 1 },
  { userId: 4, departmentId: 1 },
  { userId: 5, departmentId: 1 },
  { userId: 6, departmentId: 1 },
  { userId: 7, departmentId: 1 },
  { userId: 8, departmentId: 1 },

  // Marketing Department
  { userId: 9, departmentId: 2 },
  { userId: 10, departmentId: 2 },
  { userId: 11, departmentId: 2 },
  { userId: 12, departmentId: 2 },

  // Sales Department
  { userId: 13, departmentId: 3 },
  { userId: 14, departmentId: 3 },
  { userId: 15, departmentId: 3 },
  { userId: 16, departmentId: 3 },
  { userId: 17, departmentId: 3 },
];

const usersTeams = [
  { userId: 5, teamId: 2 },
  { userId: 6, teamId: 2 },
  { userId: 7, teamId: 2 },
  { userId: 8, teamId: 2 },

  { userId: 9, teamId: 3 },
  { userId: 10, teamId: 3 },

  { userId: 11, teamId: 4 },
  { userId: 12, teamId: 4 },
];

const usersGroups = [
  // Group 1: Book Club
  { userId: 1, groupId: 1 },
  { userId: 2, groupId: 1 },
  { userId: 3, groupId: 1 },
  { userId: 4, groupId: 1 },

  // Group 2: Couch Potato
  { userId: 1, groupId: 2 },
  { userId: 3, groupId: 2 },

  // Group 3: LOTR
  { userId: 2, groupId: 3 },
  { userId: 4, groupId: 3 },
  { userId: 5, groupId: 3 },
];

export const seedUsers = async () => {
  await writePrisma.$transaction(async (prisma) => {
    await Promise.all(
      users.map((user) =>
        prisma.user.create({
          data: {
            firstName: user.firstName,
            lastName: user.lastName,
            email: user.email,
            locationId: user.locationId,
            role: user.role as UserRole,
            reportsToId: user.reportsToId,
          },
        }),
      ),
    );
  });

  seedUserRelations();
};

const seedUserRelations = async () => {
  usersDepartments.forEach(async (userDepartment) => {
    await writePrisma.userDepartment.create({
      data: {
        ...userDepartment,
      },
    });
  });
  usersTeams.forEach(async (userTeam) => {
    await writePrisma.userTeam.create({
      data: {
        ...userTeam,
      },
    });
  });
  usersGroups.forEach(async (userGroup) => {
    await writePrisma.userGroup.create({
      data: {
        ...userGroup,
      },
    });
  });
};
